PLUS = '+'
MINUS = '-'
MUL = '*'
DIV = '/'
FLOORDIV = '//'
MOD = '%'
POWER = '**'
BINARY_AND = 'and' #TODO
BINARY_OR = 'or' #TODO
BINARY_XOR = 'xor' #TODO
BINARY_ONES_COMPLIMENT = '~' #TODO
BINARY_LEFT_SHIFT = '<<' #TODO
BINARY_RIGHT_SHIFT = '>>' #TODO
AND = 'and'
OR = 'or'
NOT = 'not'
IN = 'in' #TODO
NOT_IN = 'not in' #TODO
IS = 'is' #TODO
IS_NOT = 'is not' #TODO
TYPE_AND = '&'
TYPE_OR = '|'
TYPE_THEN = ','
LPAREN = '('
RPAREN = ')'
LSQUAREBRACKET = '['
RSQUAREBRACKET = ']'
LCURLYBRACKET = '{'
RCURLYBRACKET = '}'
COMMA = ','
COLON = ':'
DOT = '.' #TODO
RANGE = '..' #TODO
ELLIPSIS = '...' #TODO
ARROW = '->' #TODO
CAST = '::'
ASSIGN = '='
PLUS_ASSIGN = '+='
MINUS_ASSIGN = '-='
MUL_ASSIGN = '*='
DIV_ASSIGN = '/='
FLOORDIV_ASSIGN = '//='
MOD_ASSIGN = '%='
POWER_ASSIGN = '**='
EQUALS = '=='
NOT_EQUALS = '!='
LESS_THAN = '<'
GREATER_THAN = '>'
LESS_THAN_OR_EQUAL_TO = '<='
GREATER_THAN_OR_EQUAL_TO = '>='
DECORATOR = '@' #TODO
ANY = 'Any'
INT = 'Int'
DEC = 'Dec'
FLOAT = 'Float'
COMPLEX = 'Complex' #TODO
STR = 'Str'
BOOL = 'Bool'
BYTES = 'Bytes' #TODO
ARRAY = 'Array'
LIST = 'List'
TUPLE = 'Tuple' #TODO
SET = 'Set' #TODO
DICT = 'Dict'
ENUM = 'Enum' #TODO
FUNC = 'Func'
NULLTYPE = 'NullType'
TRUE = 'true'
FALSE = 'false'
NULL = 'null'
NAN = 'nan'
INF = 'inf'
NEGATIVE_INF = '-inf'
IF = 'if'
ELSE_IF = 'else if'
ELSE = 'else'
FOR = 'for' #TODO
WHILE = 'while'
SWITCH = 'switch' #TODO
CASE = 'case' #TODO
DEFAULT = 'default' #TODO
CLASS = 'class' #TODO
ACTOR = 'actor' #TODO
CONST = 'const' #TODO
NEW = 'new' #TODO
SUPER = 'super' #TODO
THIS = 'this' #TODO
RETURN = 'return'
TEST = 'test' #TODO
TRY = 'try' #TODO
CATCH = 'catch' #TODO
FINALLY = 'finally' #TODO
THEN = 'then' #TODO
YIELD = 'yield' #TODO
BREAK = 'break' #TODO
CONTINUE = 'continue' #TODO
DEL = 'del' #TODO
FROM = 'from' #TODO
IMPORT = 'import' #TODO
WILDCARD = '*' #TODO
WITH = 'with' #TODO
AS = 'as' #TODO
PASS = 'pass' #TODO
VOID = 'void' #TODO
RAISE = 'raise' #TODO
TYPE = 'type' #TODO
STRUCT = 'struct' #TODO
REQUIRE = 'require' #TODO
ENSURE = 'ensure' #TODO
OVERRIDE = 'override' #TODO
DOC = 'doc' #TODO
ABSTRACT = 'abstract' #TODO
GETTER = 'getter' #TODO
SETTER = 'setter' #TODO
ASSERT = 'assert' #TODO

ARITHMETIC_OP = (PLUS, MINUS, MUL, DIV, MOD, FLOORDIV, POWER)

ASSIGNMENT_OP = (ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, FLOORDIV_ASSIGN, MOD_ASSIGN, POWER_ASSIGN)

COMPARISON_OP = (EQUALS, NOT_EQUALS, LESS_THAN, GREATER_THAN, GREATER_THAN_OR_EQUAL_TO, LESS_THAN_OR_EQUAL_TO)

LOGICAL_OP = (AND, OR, NOT)

BINARY_OP = (BINARY_AND, BINARY_OR, BINARY_XOR, BINARY_ONES_COMPLIMENT, BINARY_LEFT_SHIFT, BINARY_RIGHT_SHIFT)

MEMBERSHIP_OP = (IN, NOT_IN)

IDENTITY_OP = (IS, IS_NOT)

TYPE_OP = (TYPE_AND, TYPE_OR, TYPE_THEN)

MULTI_WORD_OPERATORS = (IS, IS_NOT, IN, NOT_IN, NOT)

OPERATORS = (
	LPAREN, RPAREN, LSQUAREBRACKET, RSQUAREBRACKET, LCURLYBRACKET, RCURLYBRACKET,
	ARROW, COMMA, COLON, DOT, DECORATOR, CAST, RANGE, ELLIPSIS,
) + ARITHMETIC_OP + ASSIGNMENT_OP + COMPARISON_OP + LOGICAL_OP + BINARY_OP + MEMBERSHIP_OP + IDENTITY_OP + TYPE_OP

SINGLE_OPERATORS = (
	LPAREN, RPAREN, LSQUAREBRACKET, RSQUAREBRACKET, LCURLYBRACKET, RCURLYBRACKET,
	BINARY_ONES_COMPLIMENT, COMMA, DECORATOR, TYPE_AND, TYPE_OR, TYPE_THEN
)

KEYWORDS = (
	IF, ELSE, WHILE, FOR, SWITCH, CASE, CLASS, SUPER, THIS, RETURN, TEST, TRY, CATCH, FINALLY,
	THEN, YIELD, BREAK, CONTINUE, DEL, IMPORT, FROM, WITH, AS, PASS, VOID, RAISE, ACTOR, CONST,
	STRUCT, REQUIRE, ENSURE, OVERRIDE, DOC, ABSTRACT, GETTER, SETTER, ASSERT, DEFAULT, NEW, TYPE
)

MULTI_WORD_KEYWORDS = (IF, ELSE, ELSE_IF)

TYPES = (ANY, INT, DEC, FLOAT, COMPLEX, STR, BOOL, BYTES, ARRAY, LIST, TUPLE, DICT, ENUM, FUNC, NULLTYPE)

CONSTANTS = (TRUE, FALSE, NULL, NAN, INF, NEGATIVE_INF)

BUILTIN_FUNCTIONS = ('print',)

TOKEN_TYPE = 'TYPE'
NUMBER = 'NUMBER'
STRING = 'STRING'
OP = 'OP'
CONSTANT = 'CONSTANT'
NEWLINE = 'NEWLINE'
INDENT = 'INDENT'
KEYWORD = 'KEYWORD'
NAME = 'NAME'
EOF = 'EOF'

ALPHANUMERIC = 'alphanumeric'
NUMERIC = 'numeric'
OPERATIC = 'operatic'
WHITESPACE = 'whitespace'
COMMENT = 'comment'
ESCAPE = 'escape'